# Generated by Django 5.1.2 on 2024-11-10 12:07

import OpportuNest.review.authentication
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5, 'Max rating is 5'), django.core.validators.MinValueValidator(1, 'Minimum rating is 1')])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to='accounts.company')),
                ('reviewer', models.ForeignKey(on_delete=models.SET(OpportuNest.review.authentication.get_deleted_user), related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
