# Generated by Django 5.1.2 on 2024-11-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_company_review_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='feedback',
        ),
    ]
