# Generated by Django 5.1.2 on 2024-11-06 10:47

import OpportuNest.application.validators
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('job_seeker_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', cloudinary.models.CloudinaryField(max_length=255, validators=[OpportuNest.application.validators.PDFValidator()], verbose_name='file')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_seeker_profile.jobseekerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='job.job')),
            ],
        ),
    ]
